# running numbat ---------------------------------------------------------------------------------------------------------
# load numbat
library(numbat)

#rcc.1
# load data
count_mat <- readRDS('/mnt/mydata/input/rcc.1_matrix.rds')
df_allele <- read.delim('/mnt/mydata/output/rcc.1/rcc.1_allele_counts.tsv')
# run
out = run_numbat(
    count_mat, # gene x cell integer UMI count matrix
    ref_hca, # reference expression profile, a gene x cell type normalized expression level matrix
    df_allele, # allele dataframe generated by pileup_and_phase script
    genome = "hg38",
    t = 1e-5,
    ncores = 4,
    plot = TRUE,
    out_dir = '/mnt/mydata/output/rcc_1',
    max_entropy = 0.8
)

#rcc.2
count_mat <- readRDS('/mnt/mydata/input/rcc.2_matrix.rds')
df_allele <- read.delim('/mnt/mydata/output/rcc.2/rcc.2_allele_counts.tsv')
out = run_numbat(
    count_mat, # gene x cell integer UMI count matrix 
    ref_hca, # reference expression profile, a gene x cell type normalized expression level matrix
    df_allele, # allele dataframe generated by pileup_and_phase script
    genome = "hg38",
    t = 1e-5,
    ncores = 20,
    plot = TRUE,
    out_dir = '/mnt/mydata/output/rcc_2'
)

#rcc.3
count_mat <- readRDS('/mnt/mydata/input/rcc.3_matrix.rds')
df_allele <- read.delim('/mnt/mydata/output/rcc.3/rcc.3_allele_counts.tsv')
out = run_numbat(
    count_mat, # gene x cell integer UMI count matrix 
    ref_hca, # reference expression profile, a gene x cell type normalized expression level matrix
    df_allele, # allele dataframe generated by pileup_and_phase script
    genome = "hg38",
    t = 1e-5,
    ncores = 20,
    plot = TRUE,
    out_dir = '/mnt/mydata/output/rcc_3'
)

#rcc.4
count_mat <- readRDS('/mnt/mydata/input/rcc.4_matrix.rds')
df_allele <- read.delim('/mnt/mydata/output/rcc.4/rcc.4_allele_counts.tsv')
out = run_numbat(
    count_mat, # gene x cell integer UMI count matrix 
    ref_hca, # reference expression profile, a gene x cell type normalized expression level matrix
    df_allele, # allele dataframe generated by pileup_and_phase script
    genome = "hg38",
    t = 1e-5,
    ncores = 20,
    plot = TRUE,
    out_dir = '/mnt/mydata/output/rcc_4'
)

#rcc.5
count_mat <- readRDS('/mnt/mydata/input/rcc.5_matrix.rds')
df_allele <- read.delim('/mnt/mydata/output/rcc.5/rcc.5_allele_counts.tsv')
out = run_numbat(
    count_mat, # gene x cell integer UMI count matrix 
    ref_hca, # reference expression profile, a gene x cell type normalized expression level matrix
    df_allele, # allele dataframe generated by pileup_and_phase script
    genome = "hg38",
    t = 1e-5,
    ncores = 20,
    plot = TRUE,
    out_dir = '/mnt/mydata/output/rcc_5'
)

#rcc.6
count_mat <- readRDS('/mnt/mydata/input/rcc.6_matrix.rds')
df_allele <- read.delim('/mnt/mydata/output/rcc.6/rcc.6_allele_counts.tsv')
out = run_numbat(
    count_mat, # gene x cell integer UMI count matrix 
    ref_hca, # reference expression profile, a gene x cell type normalized expression level matrix
    df_allele, # allele dataframe generated by pileup_and_phase script
    genome = "hg38",
    t = 1e-5,
    ncores = 20,
    plot = TRUE,
    out_dir = '/mnt/mydata/output/rcc_6'
)

#rcc.7
count_mat <- readRDS('/mnt/mydata/input/rcc.7_matrix.rds')
df_allele <- read.delim('/mnt/mydata/output/rcc.7/rcc.7_allele_counts.tsv')
out = run_numbat(
    count_mat, # gene x cell integer UMI count matrix 
    ref_hca, # reference expression profile, a gene x cell type normalized expression level matrix
    df_allele, # allele dataframe generated by pileup_and_phase script
    genome = "hg38",
    t = 1e-5,
    ncores = 20,
    plot = TRUE,
    out_dir = '/mnt/mydata/output/rcc_7'
)

#rcc.8
count_mat <- readRDS('/mnt/mydata/input/rcc.8_matrix.rds')
df_allele <- read.delim('/mnt/mydata/output/rcc.8/rcc.8_allele_counts.tsv')
out = run_numbat(
    count_mat, # gene x cell integer UMI count matrix 
    ref_hca, # reference expression profile, a gene x cell type normalized expression level matrix
    df_allele, # allele dataframe generated by pileup_and_phase script
    genome = "hg38",
    t = 1e-5,
    ncores = 20,
    plot = TRUE,
    out_dir = '/mnt/mydata/output/rcc_8'
)
